version: '3.8'

services:
  backend:
    build: 
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=employees
    networks:
      - employee-app-network

  frontend:
    build: 
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - employee-app-network


networks:
  employee-app-network: