version: '3.8'

services:
  backend:
    build: 
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=employee_db
    depends_on:
      - mysql
    networks:
      - employee-app-network

  frontend:
    build: 
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - employee-app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=employee_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - employee-app-network

volumes:
  mysql-data:

networks:
  employee-app-network: